config/routes.rb
Neurosci::Application.routes.draw do

  get "episode_pages/eventhub"
  get "episode_pages/rushton"
  get "episode_pages/outreach"
  get "episode_pages/smith"
  get "episode_pages/social"
  get "episode_pages/colloquium"

  get "resource_pages/resourcehub"
  get "resource_pages/resresource"
  get "resource_pages/links"
  get "resource_pages/articles"
  get "resource_pages/cores"
  
  get "event_pages/calendar"
  get "event_pages/rushton"
  get "event_pages/outreach"
  get "event_pages/smith"
  get "event_pages/social"
  get "event_pages/colloquium"
  get "event_pages/eventhub"

  get "about_pages/abouthub"
  get "about_pages/history"
  get "about_pages/affliates"
  get "about_pages/focus"
  
  get "students_pages/studenthub"
  get "students_pages/tribeta"
  get "students_pages/nusa"
  get "students_pages/ngsa"
  get "students_pages/nsresources"
  get "students_pages/outreach"
  get "students_pages/bee"
  get "students_pages/awareness"
  get "students_pages/fair"
  get "students_pages/constitution"
  get "students_pages/bylaws"
  get "students_pages/gsac"

  get "prospect_pages/about"
  get "prospect_pages/admission"
  get "prospect_pages/finaid"
  get "prospect_pages/curriculum"
  get "prospect_pages/prospecthub"
  get "prospect_pages/faq"

  
  root to: 'homes#show'
  resources :people do
    
    member do
      get '/people/*user_name', to: 'people#show_details'
    end

    resources :pubs, except: [:create, :new, :edit, :destroy]

  end
  resources :articles
  resources :pubs

  namespace :sekret do
    resources :people do
      resources :pubs
    end
  end

  get ':postion/:user_name' => "people#show"
  

  

end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :pubs
	default_scope { order('lname') }
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

	def show_details
		@person = Person.find_by(user_name: params[:user_name])
	end

	def index
		@people = Person.all

		if params[:filter_by]
    		@people = Person.where(:position => params[:filter_by])
  		else
    		@people = Person.all
  		end
	end

	def show
		@person = Person.find(params[:id])
		
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(person_params)

		if @person.save
			flash[:notice] = "Person created successfully!"
			redirect_to person_path(@person)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@person = Person.find(params[:id])
	end

	def update
		@person = Person.find(params[:id])

		if @person.update(person_params)
			redirect_to person_path(@person)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		person = Person.find(params[:id])
		person.destroy
		redirect_to people_path
	end




	private
	def person_params
		params.require(:person).permit(
			:fname, :lname, :user_name, :auth_id, :school, :building, 
			:office, :phone, :p1, :p2, :boss, :interest, :research,
			:position, :title, :prefix, :thumbnail, :banner, :focus1, :focus2, :focus3)
	end


end

app/controllers/sekret/people_controller.rb
class Sekret::PeopleController < ApplicationController
	def index
		@people = Person.all

		if params[:filter_by]
    		@people = Person.where(:position => params[:filter_by])
  		else
    		@people = Person.all
  		end
	end

	def show
		@person = Person.find(params[:id])
		
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(person_params)

		if @person.save
			flash[:notice] = "Person created successfully!"
			redirect_to sekret_person_path(@person)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@person = Person.find(params[:id])
	end

	def update
		@person = Person.find(params[:id])

		if @person.update(person_params)
			redirect_to sekret_person_path(@person)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		person = Person.find(params[:id])
		person.destroy
		redirect_to sekret_people_path
	end




	private
	def person_params
		params.require(:person).permit(
			:fname, :lname, :user_name, :auth_id, :school, :building, 
			:office, :phone, :p1, :p2, :boss, :interest, :research,
			:position, :title, :prefix, :thumbnail, :banner, :focus1, :focus2, :focus3)
	end
end

app/controllers/sekret/pubs_controller.rb
class Sekret::PubsController < ApplicationController
	def index
		@pubs = Pub.all
	end

	def show
		@pub = Pub.find(params[:id])
	end

	def new
		@person = Person.find(params[:person_id])
		@pub = @person.pubs.new
	end

	def create
		
		@pub = Pub.new(pub_params)

		if @pub.save
			flash[:notice] = "Article created successfully!"
			redirect_to sekret_pub_path(@pub)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@pub = Pub.find(params[:id])
	end

	def update
		@pub = Pub.find(params[:id])

		if @pub.update(pub_params)
			redirect_to sekret_pub_path(@pub)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		pub = Pub.find(params[:id])
		pub.destroy
		redirect_to sekret_people_path
	end




	private
	def pub_params
		params.require(:pub).permit(
			:pubmed_id, :journal, :pages, :date, :type, :link, :authors,
			:title, :notes, :auth_id, :person_id)
	end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sekret/people_helper.rb
module Sekret::PeopleHelper
end

app/helpers/sekret/pubs_helper.rb
module Sekret::PubsHelper
end

app/views/sekret/people/_form.html.erb
<%= form_for(person) do |f| %>
	<fieldset>
		<%= f.label :prefix %>
		<%= f.text_field :prefix %>
	</fieldset>
	
	<fieldset>
		<%= f.label :First_Name %>
		<%= f.text_field :fname %>
	</fieldset>

	<fieldset>
		<%= f.label :last_name %>
		<%= f.text_field :lname %>
	</fieldset>

	<fieldset>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</fieldset>

	<fieldset>
		<%= f.label :user_name %>
		<%= f.text_field :user_name %>
	</fieldset>

	<fieldset>
		<%= f.label :author_name %>
		<%= f.text_field :auth_id %>
	</fieldset>

	<fieldset>
		<%= f.label :school %>
		<%= f.text_field :school %>
	</fieldset>

	<fieldset>
		<%= f.label :position %>
		<%= f.select :position, ['faculty', 'staff', 'postdoc', 'graduate student', 'lab tech'] %>
	</fieldset>

	<fieldset>
		<%= f.label :building %>
		<%= f.text_field :building %>
	</fieldset>

	<fieldset>
		<%= f.label :office %>
		<%= f.text_field :office %>
	</fieldset>

	<fieldset>
		<%= f.label :phone %>
		<%= f.text_field :phone %>
	</fieldset>

	<fieldset>
		<%= f.label :pi1 %>
		<%= f.text_field :pi1 %>
	</fieldset>

	<fieldset>
		<%= f.label :pi2 %>
		<%= f.text_field :pi2 %>
	</fieldset>

	<fieldset>
		<%= f.label :focus %>
		<%= f.text_field :focus1 %>
	</fieldset>

	<fieldset>
		<%= f.label :focus %>
		<%= f.text_field :focus2 %>
	</fieldset>

	<fieldset>
		<%= f.label :focus %>
		<%= f.text_field :focus3 %>
	</fieldset>

	<fieldset>
		<%= f.label :boss %>
		<%= f.text_field :boss %>
	</fieldset>

	<fieldset>
		<%= f.label :interest %>
		<%= f.text_area :interest %>
	</fieldset>

	<fieldset>
		<%= f.label :research %>
		<%= f.text_area :research %>
	</fieldset>

	<fieldset>
		<%= f.label :thumbnail %>
		<%= f.file_field :thumbnail %>
	</fieldset>

	<fieldset>
		<%= f.label :banner %>
		<%= f.file_field :banner %>
	</fieldset>

	<%= f.submit %>
<% end %>

app/views/sekret/people/edit.html.erb
<% provide(:title, "Edit: " @person.name) %>
<h2>Edit Entity</h2>

<%= render 'form', person: @person %>

app/views/sekret/people/index.html.erb
<h1>Directory</h1>

<div class="filter_div">
	<div class="filter btn btn-default btn-directory active"><%= link_to "New entry", new_sekret_person_path %></div>
	<div class="filter btn btn-default btn-directory active"><%= link_to "Full Listing", sekret_people_path %></div>
	<div class="filter btn btn-default btn-directory active"><%= link_to "Faculty", sekret_people_path(:filter_by => :faculty), {:method => :get} %></div>
	<div class="filter btn btn-default btn-directory active"><%= link_to "Postdocs", sekret_people_path(:filter_by => :postdoc), {:method => :get} %></div>
	<div class="filter btn btn-default btn-directory active"><%= link_to "Grad Students", sekret_people_path(:filter_by => :'graduate student'), {:method => :get} %></div>
	<div class="filter btn btn-default btn-directory active"><%= link_to "Affiliates", sekret_people_path(:filter_by => :affiliates), {:method => :get} %></div>
	<div class="filter btn btn-default btn-directory active"><%= link_to "Staff", sekret_people_path(:filter_by => :staff), {:method => :get} %></div>

</div>

<table class="people table-striped">
	
	<tbody>
		<% @people.each do |person| %>
		  <tr class="people_row">
		  	<td>
		  		<div class="portrait">
		  			<%= image_tag("#{person.user_name}S.jpg") %>
		  		</div>
		  	</td>
		  	<td class="names">
		  		<div class="inner">
		  			<p><%= link_to sekret_person_path(person) do %>
  						<strong><%= person.fname %> <%= person.lname %></strong>
					<% end %></p>
		  			<p><%= person.title %></p>
		  			<p><%= person.position.capitalize %></p>
		  		</div>
		  	</td>
		  	<td class="stats">
		  		<div class="inner">
		  			<p><%= person.school %></p>
		  			<p><%= person.building %> <%= person.office %></p>
		  			<p><%= person.phone %></p>
		  		</div>
		  	</td>
		  	<td class="mail">
		  		<div class="inner">
		  			<%= person.user_name %>@neuro.fsu.edu
		  		</div>
		  	</td>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/sekret/people/new.html.erb
<% provide(:title, "New Personel Entry") %>
<h2>New Entity</h2>

<%= render 'form', person: @person %>

app/views/sekret/people/show.html.erb
<%= provide(:title,  @person.lname) %>



<div id="main_con" class="container">

<div class="row">

	<div>
		<!-- # Space for accepting student text -->
	</div>

   <div id="person_left" class="col-sm-6 col-md-7">
   	   <div class="profile">
   		<%= image_tag("#{@person.user_name}.jpg") %>
   	   </div>
   </div>
   
   <p> </p>

   <div id="person_right" class="col-sm-6 col-md-5 profile_info">
   		<h2><%= @person.prefix %> <%= @person.fname %> <%= @person.lname %></h2>
		<h4><%= @person.title %></h4>
		<dl>
			<dd><%= @person.position.capitalize %></dd>
			<dd><%= @person.school %></dd>
			<dd><%= @person.building %> <%= @person.office %></dd>
			<dd><%= @person.phone %></dd>
			<dd><%= @person.user_name %></dd>
		</dl>
   </div>
  </div>

  <div class="row">
  		<div class="col-sm-6 profile_desc">
  			<p> </p>
  			<dl>
				<dt>Interest</dt>
				<dd><%= @person.interest %></dd>

				<dt>Current Reseach</dt>
				<dd><%= @person.research %></dd>

				<dt>Recent Publications</dt>
				<dd>
					<table class="table-striped">
		  				<tbody>
		  					<% @person.pubs.each do |pub| %>
									<tr>
										<td><%= pub.authors %>, <%= pub.title %>, <%= pub.journal %>, <%= pub.date %> </td> </tr>
									<% end %>
		  				</tbody>
		  			</table>
  					<%= link_to 'Add new Publication', new_sekret_person_pub_path(@person) %>

				</dd>

				
			</dl>

  		</div>

  		<div class="col-sm-6">
  			<!--Lab Links and people go here. -->
  		</div>

  </div>

</div>