config/routes.rb
Neurosci::Application.routes.draw do

  get "episode_pages/eventhub"
  get "episode_pages/rushton"
  get "episode_pages/outreach"
  get "episode_pages/smith"
  get "episode_pages/social"
  get "episode_pages/colloquium"

  get "resource_pages/resourcehub"
  get "resource_pages/resresource"
  get "resource_pages/links"
  get "resource_pages/articles"
  get "resource_pages/cores"
  
  get "event_pages/calendar"
  get "event_pages/rushton"
  get "event_pages/outreach"
  get "event_pages/smith"
  get "event_pages/social"
  get "event_pages/colloquium"
  get "event_pages/eventhub"

  get "about_pages/abouthub"
  get "about_pages/history"
  get "about_pages/affliates"
  get "about_pages/focus"
  
  get "students_pages/studenthub"
  get "students_pages/tribeta"
  get "students_pages/nusa"
  get "students_pages/ngsa"
  get "students_pages/nsresources"
  get "students_pages/outreach"
  get "students_pages/bee"
  get "students_pages/awareness"
  get "students_pages/fair"
  get "students_pages/constitution"
  get "students_pages/bylaws"
  get "students_pages/gsac"

  get "prospect_pages/about"
  get "prospect_pages/admission"
  get "prospect_pages/finaid"
  get "prospect_pages/curriculum"
  get "prospect_pages/prospecthub"
  get "prospect_pages/faq"

  
  root to: 'homes#show'
  resources :people do
    
    member do
      get '/people/*user_name', to: 'people#show_details'
    end

    resources :pubs, except: [:create, :new, :edit, :destroy]

  end
  resources :articles
  resources :pubs

  namespace :sekret do
    resources :people do
      resources :pubs
    end
  end

  get ':postion/:user_name' => "people#show"
  

  

end

app/models/archive.rb
class Archive < ActiveRecord::Base
	belongs_to :person
	belongs_to :article
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_one :people
end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :pubs
	default_scope { order('lname') }
end

app/models/pub.rb
class Pub < ActiveRecord::Base
  belongs_to :person
  default_scope { order('date') }
end

app/controllers/about_pages_controller.rb
class AboutPagesController < ApplicationController
  def abouthub
  end

  def history
  end

  def affliates
  end

  def focus
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)

		if @article.save
			flash[:notice] = "Article created successfully!"
			redirect_to article_path(@article)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to article_path(@article)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		article = Article.find(params[:id])
		article.destroy
		redirect_to people_path
	end




	private
	def article_params
		params.require(:article).permit(
			:pubmed_id, :journal, :pages, :date, :type, :link, :authors,
			:title, :notes, :auth_id)
	end
end

app/controllers/episode_pages_controller.rb
class EpisodePagesController < ApplicationController
  def eventhub
  end

  def rushton
  end

  def outreach
  end

  def smith
  end

  def social
  end

  def colloquium
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

	def show_details
		@person = Person.find_by(user_name: params[:user_name])
	end

	def index
		@people = Person.all

		if params[:filter_by]
    		@people = Person.where(:position => params[:filter_by])
  		else
    		@people = Person.all
  		end
	end

	def show
		@person = Person.find(params[:id])
		
	end

	def new
		@person = Person.new
	end

	def create
		@person = Person.new(person_params)

		if @person.save
			flash[:notice] = "Person created successfully!"
			redirect_to person_path(@person)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@person = Person.find(params[:id])
	end

	def update
		@person = Person.find(params[:id])

		if @person.update(person_params)
			redirect_to person_path(@person)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		person = Person.find(params[:id])
		person.destroy
		redirect_to people_path
	end




	private
	def person_params
		params.require(:person).permit(
			:fname, :lname, :user_name, :auth_id, :school, :building, 
			:office, :phone, :p1, :p2, :boss, :interest, :research,
			:position, :title, :prefix, :thumbnail, :banner, :focus1, :focus2, :focus3)
	end


end

app/controllers/prospect_pages_controller.rb
class ProspectPagesController < ApplicationController
  def about
  end

  def admission
  end

  def finaid
  end

  def curriculum
  end

  def prospecthub
  end

  def faq
  end
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController

	def index
		@pubs = Pub.all
	end

	def show
		@pub = Pub.find(params[:id])
	end

	def new
		@person = Person.find(params[:person_id])
		@pub = @person.pubs.new
	end

	def create
		
		@pub = Pub.new(pub_params)

		if @pub.save
			flash[:notice] = "Article created successfully!"
			redirect_to pub_path(@pub)
		else
			render :new, status: :unprocessable_entity
		end
	end

	def edit
		@pub = Pub.find(params[:id])
	end

	def update
		@pub = Pub.find(params[:id])

		if @pub.update(pub_params)
			redirect_to pub_path(@pub)
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		pub = Pub.find(params[:id])
		pub.destroy
		redirect_to people_path
	end




	private
	def pub_params
		params.require(:pub).permit(
			:pubmed_id, :journal, :pages, :date, :type, :link, :authors,
			:title, :notes, :auth_id, :person_id)
	end
end

app/controllers/resource_pages_controller.rb
class ResourcePagesController < ApplicationController
  def resourcehub
  end

  def resresource
  end

  def links
  end

  def articles
  end

  def cores
  end
end

app/helpers/about_pages_helper.rb
module AboutPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/episode_pages_helper.rb
module EpisodePagesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/prospect_pages_helper.rb
module ProspectPagesHelper
end

app/helpers/pubs_helper.rb
module PubsHelper
end

app/helpers/resource_pages_helper.rb
module ResourcePagesHelper
end

app/helpers/students_pages_helper.rb
module StudentsPagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>

	<fieldset>
		<%= f.label :pubmed_id %>
		<%= f.text_field :pubmed_id %>
	</fieldset>

	<fieldset>
		<%= f.label :journal %>
		<%= f.text_field :journal %>
	</fieldset>

	<fieldset>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</fieldset>

	<fieldset>
		<%= f.label :auth_id %>
		<%= f.text_area :auth_id %>
	</fieldset>

	<fieldset>
		<%= f.label :authors %>
		<%= f.text_area :authors %>
	</fieldset>

	<fieldset>
		<%= f.label :pages %>
		<%= f.text_field :pages %>
	</fieldset>

	<fieldset>
		<%= f.label :date %>
		<%= f.text_field :date %>
	</fieldset>

	<fieldset>
		<%= f.label :type %>
		<%= f.text_field :type %>
	</fieldset>

	<fieldset>
		<%= f.label :link %>
		<%= f.text_field :link %>
	</fieldset>

	<fieldset>
		<%= f.label :notes %>
		<%= f.text_area :notes %>
	</fieldset>

	

	<%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "Edit Article Information") %>
<h2>Edit Article</h2>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<% provide(:title, "Articles, Full List") %>
<h1>List of Program Produced Articles</h1>

<div>
	<%= link_to "Create a new entry", new_article_path %>
</div>

<table class="table-striped">
	<tbody>
		<% @articles.each do |article| %>
		  <tr>
		  	<div><td><p><%= link_to(article) do %>
  						<strong><%= article.title %></strong>
					<% end %></p></td></div>
		  	<div>
		  		<td><%= article.authors %></td>
		  	</div>
		  	<div>
		  		<td><%= article.journal %></td>
		  		<td><%= article.pages %></td>
		  		<td><%= article.date %></td>
		  		<td><%= article.pubmed_id %></td>
		  	</div>
		  </tr>
		<% end %>
	</tbody>
</table>

app/views/articles/new.html.erb
<% provide(:title, "New Article") %>
<h2>New Article</h2>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<% provide(:title, "Article Details") %>
<h1><%= @article.title %></h1>
<h2><%= @article.authors %></h2>

<dl>
	<dt>title</dt>
	<dd><%= @article.title %></dd>

	<dt>journal</dt>
	<dd><%= @article.journal %></dd>

	<dt>authors</dt>
	<dd><%= @article.authors %></dd>

	<dt>Pages</dt>
	<dd><%= @article.pages %></dd>

	<dt>date</dt>
	<dd><%= @article.date %></dd>

	<dt>link</dt>
	<dd><%= @article.link %></dd>

	<dt>Notes</dt>
	<dd><%= @article.title %></dd>
</dl>

<div>
	<%= link_to "Show All", article_path %>
</div>